CREATE TABLE consumo (
                         id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         id_comunidade  NUMBER NOT NULL,
                         id_energia     NUMBER NOT NULL,
                         quantidade     NUMBER NOT NULL,

                         created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                         FOREIGN KEY (id_comunidade) REFERENCES comunidade (id),
                         FOREIGN KEY (id_energia) REFERENCES energia (id)
)

-- Triggers

CREATE
    OR REPLACE TRIGGER consumo_before_update
    BEFORE
        UPDATE ON consumo
    FOR EACH ROW
BEGIN
    :NEW
        .updated_at := CURRENT_TIMESTAMP;
END;
/