-- Flyway Migration Script: V1__initial_schema.sql

-- Create table for communities
CREATE TABLE comunidade
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR2(100) NOT NULL,
    localizacao    VARCHAR2(200),
    populacao      NUMBER,
    acesso_energia VARCHAR2(50)
);

-- Create table for energy projects
CREATE TABLE projeto
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR2(100) NOT NULL,
    descricao     VARCHAR2(500),
    tipo          VARCHAR2(50), -- e.g., solar, eolica, etc.
    data_inicio   DATE,
    data_termino  DATE,
    comunidade_id NUMBER,
    FOREIGN KEY (comunidade_id) REFERENCES comunidade (id) ON DELETE CASCADE
);

-- Create table for devices installed in the community (e.g., solar panels, batteries)
CREATE TABLE dispositivo
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo          VARCHAR2(50), -- e.g., painel_solar, bateria, medidor
    modelo        VARCHAR2(100),
    capacidade    NUMBER,       -- for example, wattage for solar panels
    comunidade_id NUMBER,
    projeto_id    NUMBER,
    FOREIGN KEY (comunidade_id) REFERENCES comunidade (id) ON DELETE CASCADE,
    FOREIGN KEY (projeto_id) REFERENCES projeto (id) ON DELETE SET NULL
);

-- Create table for energy usage data (e.g., tracking daily or monthly consumption)
CREATE TABLE consumo_energia
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data           DATE NOT NULL,
    consumo_kwh    NUMBER, -- energy consumed in kilowatt-hours
    dispositivo_id NUMBER,
    FOREIGN KEY (dispositivo_id) REFERENCES dispositivo (id) ON DELETE CASCADE
);
-- Flyway Migration Script: V1__initial_schema.sql

-- Create table for communities
CREATE TABLE comunidade
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR2(100) NOT NULL,
    localizacao    VARCHAR2(200),
    populacao      NUMBER,
    acesso_energia VARCHAR2(50)
);

-- Create table for energy projects
CREATE TABLE projeto
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR2(100) NOT NULL,
    descricao     VARCHAR2(500),
    tipo          VARCHAR2(50), -- e.g., solar, eolica, etc.
    data_inicio   DATE,
    data_termino  DATE,
    comunidade_id NUMBER,
    FOREIGN KEY (comunidade_id) REFERENCES comunidade (id) ON DELETE CASCADE
);

-- Create table for devices installed in the community (e.g., solar panels, batteries)
CREATE TABLE dispositivo
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo          VARCHAR2(50), -- e.g., painel_solar, bateria, medidor
    modelo        VARCHAR2(100),
    capacidade    NUMBER,       -- for example, wattage for solar panels
    comunidade_id NUMBER,
    projeto_id    NUMBER,
    FOREIGN KEY (comunidade_id) REFERENCES comunidade (id) ON DELETE CASCADE,
    FOREIGN KEY (projeto_id) REFERENCES projeto (id) ON DELETE SET NULL
);

-- Create table for energy usage data (e.g., tracking daily or monthly consumption)
CREATE TABLE consumo_energia
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data           DATE NOT NULL,
    consumo_kwh    NUMBER, -- energy consumed in kilowatt-hours
    dispositivo_id NUMBER,
    FOREIGN KEY (dispositivo_id) REFERENCES dispositivo (id) ON DELETE CASCADE
);

-- Create table for maintenance and inspections of devices
CREATE TABLE manutencao
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data           DATE NOT NULL,
    descricao      VARCHAR2(500),
    dispositivo_id NUMBER,
    FOREIGN KEY (dispositivo_id) REFERENCES dispositivo (id) ON DELETE CASCADE
);

-- Create table for user accounts and access logs if the platform requires user management
CREATE TABLE usuario
(
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR2(100) NOT NULL,
    email     VARCHAR2(150) UNIQUE NOT NULL,
    senha     VARCHAR2(150) NOT NULL,     -- password, assuming it's hashed
    permissao VARCHAR2(20) DEFAULT 'user' -- e.g., 'user', 'admin'
);

-- Create a table for logging user access and actions
CREATE TABLE log_acesso
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER,
    acao       VARCHAR2(500),
    data       DATE DEFAULT SYSDATE,
    FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE SET NULL
);

-- Create table for maintenance and inspections of devices
CREATE TABLE manutencao
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data           DATE NOT NULL,
    descricao      VARCHAR2(500),
    dispositivo_id NUMBER,
    FOREIGN KEY (dispositivo_id) REFERENCES dispositivo (id) ON DELETE CASCADE
);

-- Create table for user accounts and access logs if the platform requires user management
CREATE TABLE usuario
(
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR2(100) NOT NULL,
    email     VARCHAR2(150) UNIQUE NOT NULL,
    senha     VARCHAR2(150) NOT NULL,     -- password, assuming it's hashed
    permissao VARCHAR2(20) DEFAULT 'user' -- e.g., 'user', 'admin'
);

-- Create a table for logging user access and actions
CREATE TABLE log_acesso
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER,
    acao       VARCHAR2(500),
    data       DATE DEFAULT SYSDATE,
    FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE SET NULL
);
